### ISSUE TITLE
Value Error on viewing NME videos with direct URL when Gloss WebView is set on True

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1430]
https://signbank.cls.ru.nl/dictionary/protected_media/glossvideo/NGT/30/300-B-48928_nme_0.mp4

I am getting value error when viewing the video on Incognitio mode or obtaining URL via signCollect intranet.

```
Environment:


Request Method: GET
Request URL: http://signbank.cls.ru.nl/dictionary/protected_media/glossvideo/NGT/30/300-B-48928_nme_0.mp4

Django Version: 4.2.16
Python Version: 3.12.2
Installed Applications:
('colorfield',
 'modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'corsheaders',
 'reversion',
 'tagging',
 'guardian',
 'bootstrap3',
 'django_summernote',
 'signbank.dictionary',
 'signbank.feedback',
 'signbank.pages',
 'signbank.attachments',
 'signbank.video')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'signbank.pages.middleware.PageFallbackMiddleware',
 'reversion.middleware.RevisionMiddleware',
 'django.middleware.common.CommonMiddleware')



Traceback (most recent call last):
  File "/var/www/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/repo/signbank/dictionary/views.py", line 2275, in protected_media
    gloss_pk = int(filename.split('.')[-2].split('-')[-1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
Exception Type: ValueError at /dictionary/protected_media/glossvideo/NGT/30/300-B-48928_nme_0.mp4
Exception Value: invalid literal for int() with base 10: '48928_nme_0'

**Comment by susanodd** [comment]
This is solved in this pull request #1419

**Comment by susanodd** [comment]
@rem0g is this a high priority? It concerns a (public) link to a kind of video file.

I fixed this in the Public View pull request.

If this is a high priority, I need to split the code for `protected_media` into a separate branch, to speed up the review.

**Comment by susanodd** [comment]
@rem0g this should be working for you now,.

It will also work when the new perspective NME videos are available. @Woseseltops is working on that.
