### ISSUE TITLE
Running tests in production container doesn't work

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#882]
When the tests are run as part of `deploy.sh` I get:

```
Using existing test database for alias 'default'...
FIELDS: ['role']
FIELDS: ['hsAperture', 'hsFingConf2', 'hsFingConf', 'hsFingSel2', 'hsFingSel', 'hsFingUnsel', 'hsNumSel', 'hsSpread', 'hsThumb']
Traceback (most recent call last):
  File "/var/www/env/lib/python3.6/site-packages/django/db/models/options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'hsAperture_fk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/repo/bin/develop.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/var/www/env/lib/python3.6/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/var/www/env/lib/python3.6/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/var/www/env/lib/python3.6/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/var/www/env/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/var/www/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/www/env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/www/env/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/var/www/repo/signbank/dictionary/migrations/0039_auto_20200910_1020.py", line 59, in move_fieldchoice_choice
    move_fieldchoice_choice_for_class(apps, schema_editor, Handshape)
  File "/var/www/repo/signbank/dictionary/migrations/0039_auto_20200910_1020.py", line 43, in move_fieldchoice_choice_for_class
    category = klass._meta.get_field(field+'_fk').field_choice_category
  File "/var/www/env/lib/python3.6/site-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Handshape has no field named 'hsAperture_fk'

```

Some extra hints:
* The last deploy was done Dec 19, so it's likely this problem was introduced in a commit after that time.
* This seems to be related to migrations. These migrations (which are on the server and applied, according to `develop.py showmigrations` ) seem important 
  * https://github.com/Signbank/Global-signbank/blob/b2a7158739818bb0e8e95ad93d24f307c3c0b18b/signbank/dictionary/migrations/0038_auto_20201029_1217.py 
  * https://github.com/Signbank/Global-signbank/blob/b2a7158739818bb0e8e95ad93d24f307c3c0b18b/signbank/dictionary/migrations/0044_auto_20201125_1350.py

**Comment by susanodd** [comment]
That's very strange.
The numbers in the names of the commits are not sequential. But the dependencies are correct.
None of the _fk fields exist anymore.
I don't find any hsAperture_fk in anything after the commit 0044....

**Comment by susanodd** [comment]
Did you create a new test database?

The test database should not run any migrations!!!!!!
(Because it can't run the migrations anymore because the original fields don't exist. It will always fail.)

**Comment by susanodd** [comment]
There are also (related to field choices) commits on the feedback model. Those should have also been applied to the test database. Those migrations were included in the merge/commits at the same time as the ones on dictionary.

**Comment by susanodd** [comment]
https://github.com/Signbank/Global-signbank/issues/724#issuecomment-1352904152

**Comment by susanodd** [comment]
@Woseseltops I created a new test database.

The above error (this issue) does not happen.
But now upon running the tests it gets 24 errors about Cannot operate on a closed database.

I tried the tests on the master branch on my local machine and it does not have this problem.

**Comment by susanodd** [comment]
My local computer does not get the field choice error.
This field choice tests are about the

**Comment by susanodd** [comment]
It looks like the migrations for the new languages have not been applied on Global.
On my local computer, I have field choice name fields for all five languages.
But on the Global admin, there are no fields for the two new languages.
@vanlummelhuizen do you have any recollection of this?

(The tests run for all declared interface languages.)

**Comment by susanodd** [comment]
The tests also experience problems with videos.
"Error resizing video: " (feedback message)

**Comment by susanodd** [comment]
Okay, the field choice tests work again.
It needed to make use of the ADMIN_URL setting in the tests. 
Plus ignore missing model translations in the FieldChoice model. (See above.)

The only broken tests is #842 

- `AssertionError: Lists differ: ['SWITCH_TO_MYSQL'] != []`

Since that's already an issue this issue can be closed, @Woseseltops

**Comment by susanodd** [comment]
I created a new issue for the remaining problems.
