### ISSUE TITLE
Test error: incorrect assumption about existing location

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#926]
```======================================================================
ERROR: test_create_and_delete_utf8_video (signbank.dictionary.tests.VideoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 950, in test_create_and_delete_utf8_video
    videofile = open(settings.WRITABLE_FOLDER+'test_data/video.mp4','rb')
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/writable/test_data/video.mp4'

======================================================================
ERROR: test_create_and_delete_video (signbank.dictionary.tests.VideoTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 868, in test_create_and_delete_video
    videofile = open(settings.WRITABLE_FOLDER+'test_data/video.mp4','rb')
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/writable/test_data/video.mp4'
```

I guess the test should create this folder if it does not exist?

**Comment by susanodd** [comment]
This folder should exist under writable. There are test data there that are used by the tests.
Copy from Global.

**Comment by susanodd** [comment]
I'll revise it so if the test_data is missing it doesn't do the test.

**Comment by susanodd** [comment]
This is fixed.
