### ISSUE TITLE
Test error: 'Boolean field not defined'

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#927]
Happens three times, I'm guessing an extra import is necessary with the new Django?

```
======================================================================
ERROR: test_CRUD (signbank.dictionary.tests.BasicCRUDTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 92, in test_CRUD
    client.post('/dictionary/update/gloss/'+str(new_gloss.pk),{'id':'handedness','value':new_value_handedness})
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 852, in post
    response = super().post(
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 441, in post
    return self.generic(
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 541, in generic
    return self.request(**r)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 810, in request
    self.check_exception(response)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 663, in check_exception
    raise exc_value
  File "/var/www/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/repo/signbank/dictionary/update.py", line 387, in update_gloss
    if isinstance(gloss._meta.get_field(field),BooleanField):
NameError: name 'BooleanField' is not defined
```

```
======================================================================
ERROR: test_field_types (signbank.dictionary.tests.RevisionHistoryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 2877, in test_field_types
    client.post('/dictionary/update/gloss/' + str(new_gloss.pk), update_data)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 852, in post
    response = super().post(
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 441, in post
    return self.generic(
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 541, in generic
    return self.request(**r)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 810, in request
    self.check_exception(response)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 663, in check_exception
    raise exc_value
  File "/var/www/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/repo/signbank/dictionary/update.py", line 387, in update_gloss
    if isinstance(gloss._meta.get_field(field),BooleanField):
NameError: name 'BooleanField' is not defined

```

```
======================================================================
ERROR: test_handshape_choices (signbank.dictionary.tests.HandshapeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 1625, in test_handshape_choices
    self.client.post('/dictionary/update/gloss/'+str(glosses[1].pk),{'id':'domhndsh','value':new_handshape_value_string})
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 852, in post
    response = super().post(
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 441, in post
    return self.generic(
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 541, in generic
    return self.request(**r)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 810, in request
    self.check_exception(response)
  File "/var/www/env/lib/python3.10/site-packages/django/test/client.py", line 663, in check_exception
    raise exc_value
  File "/var/www/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/repo/signbank/dictionary/update.py", line 387, in update_gloss
    if isinstance(gloss._meta.get_field(field),BooleanField):
NameError: name 'BooleanField' is not defined
```

**Comment by susanodd** [comment]
That's issue #925. (See errors from update.py in the updatedjango branch.)

**Comment by susanodd** [comment]
ALL THE TESTS WORK NOW ON MY LOCAL PYCHARM RUNSERVER!!!!

```
Ran 51 tests in 329.303s

OK
```

**Comment by susanodd** [comment]
These are all fixed.
