### ISSUE TITLE
Test error: JSON is None

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#928]
Probably something related to new Django

```======================================================================
ERROR: test_DatasetListView_ECV_export_empty_dataset (signbank.dictionary.tests.ImportExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 498, in test_DatasetListView_ECV_export_empty_dataset
    json_decoded_cookies = json.loads(decoded_cookies, cls=MessageDecoder)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType``` 

```======================================================================
ERROR: test_DatasetListView_ECV_export_no_permission_change_dataset (signbank.dictionary.tests.ImportExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 581, in test_DatasetListView_ECV_export_no_permission_change_dataset
    json_decoded_cookies = json.loads(decoded_cookies, cls=MessageDecoder)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType```

```======================================================================
ERROR: test_DatasetListView_ECV_export_permission_change_dataset (signbank.dictionary.tests.ImportExportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/repo/signbank/dictionary/tests.py", line 552, in test_DatasetListView_ECV_export_permission_change_dataset
    json_decoded_cookies = json.loads(decoded_cookies, cls=MessageDecoder)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType```

**Comment by susanodd** [comment]
That's probably related to the missing test_data files. (In #926, copy the files from Global.)

**Comment by susanodd** [comment]
I tried this on my local computer. I get exactly the same error.
However, this also does not work on the page it's testing:
e.g., datasets/available?dataset_name=ASL&export_ecv=ECV
(By pressing on the export ECV button on the Datasets page.)
```
PermissionError at /datasets/available

[Errno 13] Permission denied: '/home/susan/signbank/writable/ecv/asl.ecv'
```
The directory/ (old) file has only read permissions, so a new file can't be written.
(So something might be wrong with the writable directories themselves.)
(The code itself isn't friendly because it's not printing a user error message.)

**Comment by susanodd** [comment]
This is fixed!
